FROM node:20-alpine AS builder

WORKDIR /app

ENV NODE_OPTIONS="--dns-result-order=ipv4first"

COPY package.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_OPTIONS="--dns-result-order=ipv4first"

COPY package.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist

EXPOSE 5000

ENV NODE_ENV=production

CMD ["node", "dist/server.js"]
